### ISSUE TITLE
XCTest: Stdio not output at correct point

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-corelibs-xctest#422]
**Describe the bug**
Stdio output appears to be buffered and not outputting at correct time. The easiest way to reproduce this is create a test which outputs a lot of text. You'll find that the text output appears after the `TestSuite passed` message. This only happens when running swift from the command line.

**Steps To Reproduce**
1. Create package which includes the following test
```swift
    func testPrint() {
        for i in 1..<100 {
            let string = (0..<i).map(\.description).joined()
            print(string)
        }
    }
}
```
2. Run `swift test`

**Expected behavior**
Print out of numbers should appear before `TestSuite passed` message.

**Environment (please fill out the following information)**
 - OS: macOS 12.4
 - Xcode: 13.4
 - swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0

**Comment by stmontgomery** [comment]
This symptom appears to be seen in the copy of XCTest included in Xcode, not in the "Corelibs" open source Swift version of XCTest contained in this repo. I have filed rdar://102210347 to track the issue there. But we can keep this issue open to track fixing the same problem in this repo, even though I don't think that is where the bug was originally observed.

**Comment by adam-fowler** [comment]
Yes this is a macOS issue only. On macOS XCTest outputs all of its status updates to stderr, while the corelibs version outputs to stdout. This issue could be fixed by either
- moving xctest outputs to stdout.
- running `fflush(stdout)` and `fflush(stderr)` after each test has run

**Comment by weissi** [comment]
> - moving xctest outputs to stdout.

That alone won't be good enough. Unless XCTest starts going through stdio (i.e. `fwrite`, `fputs`, `fprintf`, ...) too. And even if that were changed that wouldn't fix potential weirdness because we would lose messages when the program crashes in CI.

My recommendation would be to flush everything right after the test has ended. That way we do as much as we can to make sure the printed data actually makes it into the output (terminal/pipe/file/...).

**Comment by grynspan** [comment]
I wonder if calling [`setbuf()`](https://en.cppreference.com/w/c/io/setbuf) to change the buffering of `stdout` and/or `stderr` would help here?

**Comment by weissi** [comment]
> I wonder if calling [`setbuf()`](https://en.cppreference.com/w/c/io/setbuf) to change the buffering of `stdout` and/or `stderr` would help here?

It would if we assume that the user never touches it. I still think it can be expected from a test framework that it flushes all sorts of output buffers at the end of a test.

**Comment by grynspan** [comment]
Agreed, that seems like a reasonable thing to do as well.

**Comment by grynspan** [comment]
We've transferred this issue to Radar as rdar://102210347 and will track it as an improvement to the XCTest framework.
