### ISSUE TITLE
Possible memory leak/unintended resource exhaustion in `XCTAssertNotNil`

### ISSUE THREAD

**Issue by paulober** [apple/swift-corelibs-xctest#486]
First, I'm new to xctest so it could be that this I a feature and not a bug (or maybe caused by using it wrong)...

I created a swift package library to read a specific data format into memory. I end up with a struct that takes `5,88 GB` in memory for one input. The function creating it could possible return nil. So I added `XCTAssertNotNil(feed, "Unable to load feed into memory!")` to assert this.
But when it gets into this call, the memory usage will grow potential infinitely (I only waited until `21GB` with also a temporary spike to `33 GB` usage for some seconds). If I select pause in the debugger in Xcode it will show this XCTAssert call in the call stack as the source.

Additionally: During the intense memory allocation the debugger shows 99% CPU utilization for this PID.

**Comment by grynspan** [comment]
It sounds like you're using the version of XCTest that ships inside Xcode rather than swift-corelibs-xctest which is an open-source implementation of XCTest that is distributed with Linux/Windows toolchains. Please use Apple's Feedback Assistant to report this issue to Apple and attach the logs you're seeing (you can copy and paste a backtrace directly from Xcode's Debug Navigator.) Thanks!
